# Generated by Django 4.0.4 on 2022-05-03 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_id_alter_category_id_alter_comment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='categorie',
        ),
    ]
